### ISSUE TITLE
'click' missing error

### ISSUE THREAD

**Issue by msh5** [msh5/pipfile-sort#19]
v0.2.0

```
pipenv run pipfile-sort
Traceback (most recent call last):
  File "/home/circleci/.local/share/virtualenvs/project-zxI9dQ-Q/bin/pipfile-sort", line 5, in <module>
    from pipfile_sort import main
  File "/home/circleci/.local/share/virtualenvs/project-zxI9dQ-Q/lib/python3.9/site-packages/pipfile_sort/__init__.py", line 1, in <module>
    from click import command
ModuleNotFoundError: No module named 'click'
```

**Comment by msh5** [comment]
Should be resolved from v0.2.1.
